### PR TITLE
Agitoon url update

### LINKED ISSUE #973: Agitoon Unexpected Character
### Source information

Agitoon

### Steps to reproduce

1. Browse
2. Load Agitoon
Screenshot_20240605_081414_LNReader

### Expected behavior

Load Agitoon books

### Actual behavior

Does not load and instead results in a "JSON Parse error: Unexpected character: <" error.

### LNReader version

2.0.0-beta.1

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by error7404**
Agitoon:
 - url update (closes #973) 5c33e28
 - getting current url from the constructor from this.site to check if url changed 8617238

### CODE REVIEW

File: plugins/korean/Agitoon.ts [hunk 1]
```diff
@@ -8,14 +8,20 @@ class Agitoon implements Plugin.PluginBase {
...
     pageNo: number,
     { filters, showLatestNovels }: Plugin.PopularNovelsOptions,
   ): Promise<Plugin.NovelItem[]> {
-    const res = await fetchApi(this.site + '/novel/index.update.php', {
+    if (!Agitoon.url) {
+      Agitoon.url =
+        (await fetchApi(this.site).then(res => res.url.replace(/\/$/, ''))) ||
+        this.site;
+    }
+    const res = await fetchApi(Agitoon.url + '/novel/index.update.php', {
```
Comment (nyagami) [inline plugins/korean/Agitoon.ts:24]: I think you should call this in constructor instead.
And static keyword is not necessary tho .

Comment (error7404) [reply plugins/korean/Agitoon.ts:24]: Wouldn't that make a request when the app is opened?

Comment (nyagami) [reply plugins/korean/Agitoon.ts:24]: Im going to implement lazy initialization for plugins. so nyo
