### PR TITLE
fix: [Novel Updates]: Chapter Content

### LINKED ISSUE #1064: Issues loading and displaying chapter contents
### Source information

NovelUpdates

### Steps to reproduce

On some specific novels/links, when opening a chapter the chapter contents are not displayed.

Step 1: Open novel from library
Step 2: Open chapter from that source

### Expected behavior

The contents of the chapter load and display

### Actual behavior

It does not display the contents of the chapter, only a few of the links and text from the website

Example:
https://www.novelupdates.com/series/white-moonlight-omega-always-wants-to-possess-me/
https://app.yoru.world/en/story/181/read/3567

In app:
image

Webview:
image

### LNReader version

2.0.0-beta.2

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by Batorian**
- closes #1064.

### CODE REVIEW

**Review by rajarsheechatterjee — APPROVED** [review]

File: src/plugins/english/novelupdates.ts [hunk 1]
```diff
@@ -7,7 +6,7 @@ import { Plugin } from '@typings/plugin';
 class NovelUpdates implements Plugin.PluginBase {
   id = 'novelupdates';
   name = 'Novel Updates';
-  version = '0.7.1';
+  version = '0.8.0';
```
Comment (rajarsheechatterjee) [inline src/plugins/english/novelupdates.ts:9]:
```suggestion
  version = '0.7.2';
```
