### PR TITLE
Madara info fixes

### LINKED ISSUE #1257: No synopsis is fetched
### Source information

Citrus Aurora, Coral Boutique, Dusk Blossoms, Pastel Tales, Guavaread 

### Steps to reproduce

1. Open any of the sources indicated 
2. Click on any novel
3. No synopsis is fetched

Screenshot_2024-10-31-20-42-37-81_3c1c179116822eec69c21805387f0489

### Expected behavior

The synopsis should be fetched alongside other novel information. 

### Actual behavior

This is what happens instead.

https://github.com/user-attachments/assets/76e7585b-de47-4b4b-abb7-727957716f93

### LNReader version

2.0.0

### Android version

Android 14

### Other details

_No response_

### Acknowledgements

- [X] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [X] I have written a short but informative title.
- [X] I have updated the app to version **[1.1.19](https://github.com/LNReader/lnreader/releases/latest)**.
- [X] I have updated all installed extensions.
- [X] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).
- [X] I will fill out all of the requested information in this form.

### PR DESCRIPTION
**Pull request by error7404**
Madara: 91c3f053651bc95ccc60d0e40710ebbc6dc9a0ec
- fix summary not working for some sources (closes #1257)
- fix genres not being separated
- added artist

### CODE REVIEW

File: scripts/multisrc/madara/template.ts [hunk 1]
```diff
@@ -179,41 +179,79 @@ class MadaraPlugin implements Plugin.PluginBase {
...
     loadedCheerio('div.summary__content .code-block,script,noscript').remove();
-    const summary =
-      loadedCheerio('div.summary__content') ||
-      loadedCheerio('#tab-manga-about') ||
-      loadedCheerio('.post-content_item h5:contains("Summary")').next();
-    novel.summary = this.translateDragontea(summary).text().trim();
+    novel.summary =
+      this.translateDragontea(loadedCheerio('div.summary__content'))
+        .text()
+        .trim() ||
```
Comment (rajarsheechatterjee) [inline scripts/multisrc/madara/template.ts:236]: Should there be a check on the plugin ID for this logic?

Comment (error7404) [reply scripts/multisrc/madara/template.ts:236]: there is logic inside translateDragontea function

**Review by rajarsheechatterjee — APPROVED** [review]
