### PR TITLE
Some bug fixes and feature improvement on Linovelib Plugin

### LINKED ISSUE #1704: Linovelib Plugin - Search and Chapter Loading Failures
### Plugin

中文, 汉语, 漢語: Linovelib

### Severity

Can't load novels

### Steps to reproduce

1. Install the Linovelib plugin
2. Attempt to search for novels using the search function
3. Try to load new chapters from existing novels
4. Access the plugin's target website using the in-app webview

### Expected behavior

- Search function should return relevant novel results
- New chapters should load successfully when requested
- Plugin's target website should be accessible through the in-app webview

### Actual behavior

- Search functionality fails to return results or throws errors
- New chapter loading fails consistently
- When accessing the plugin's target website through the in-app webview, the system displays a "client disabled" message

### LNReader version

Github Action 2.0.0 (25/05/25 09:39 AM UTC) Commit: 9e81f805

### Plugin version

1.1.3

### Android version

Android 14

### Other details

This issue occurs with the Linovelib plugin. The problems seem to be related to connectivity or authentication with the target website, as evidenced by the "client disabled" message when accessing the site through the webview. This may indicate that the website has new restrictions or that the plugin's requests are being blocked.

Additional context: The mobile website (https://www.bilinovel.com/) has a strong anti-adblocking mechanism, which may be causing these issues, while the desktop website (https://www.linovelib.com/) does not seem to have such restrictions.

Image

Image

### Acknowledgements

- [x] I have searched the existing issues and this is a new ticket, **NOT** a duplicate or related to another open issue.
- [x] I have written a short but informative title.
- [x] I have updated the app to version **[2.0.0](https://github.com/LNReader/lnreader/releases/tag/v2.0.0-beta.3).**
- [x] I have updated all installed extensions.
- [x] If this is an issue with the app itself, I should be opening an issue in the [app repository](https://github.com/LNReader/lnreader/issues/new/choose).

### PR DESCRIPTION
**Pull request by ConstasJ**
Fix some problems that founded in Linovelib plugin

Problems Fixed by this PR 
- [x] Failed to load chapters in novel detail page
- [x] Searching doesn't work
- [x] Some strange replacement of some words
- [x] New Scramble methods deployed by the website

Fixes #1704

### CODE REVIEW

File: plugins/chinese/linovelib.ts [hunk 1]
```diff
@@ -50,476 +70,43 @@ class Linovelib implements Plugin.PluginBase {
...
-
-      novels.push({
-        name: novelName,
-        path: nUrl,
-        cover: novelCover,
-      });
-    });
-
-    return novels;
+    console.log(pageNo);
```
Comment (rajarsheechatterjee) [inline plugins/chinese/linovelib.ts]:
```suggestion
```
